title: Why am I here?
remote_theme: broccolini/swiss
url: https://whyamihere.philipmallis.com
plugins:
  - jekyll-remote-theme

# Theme customisation
theme_color: yellow

# Build settings
markdown: kramdown
